platform :ios, '7.0'
target 'Red' do
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'Reachability'
    pod 'MBProgressHUD'
    pod 'YYModel'
    pod 'YYCategories'
   # pod 'YYText'
    pod 'MJRefresh'
    pod 'DZNEmptyDataSet'
    pod 'SDCycleScrollView'
    pod 'TSMessages'
    pod 'REFrostedViewController'
end
